language: haskell 

env:
  global:
    secure: "az0vP8OFBJMy67HTAFmxaOTYynjsW71a4dnzYBm5ybbZAuLYr3LeE5aQ2gsO\n2X0x+sZ4gKgYUL80b4IwY7NiE9xjNP6dNeKyCltJJZnervwrCmmCgUG7gAyz\nfEyDTMrB84Q38uPFNKlAplow+X9fa4gRzoSxlftLi45wG5aKe9I="

install: sh ./builddep.sh
